### ISSUE TITLE
Rename dev.benedikt.math.bezier.curve.FloatBezierSpline to Curve

### ISSUE THREAD

**Issue by markjfisher** [Bw2801/bezier-spline-kotlin#1]
The FloatBezierCurve class is misnamed FloatBezierSpline, making it slightly confusing and requiring aliases if using the spline version in the same class.

**Comment by benedikt-wueller** [comment]
Issue resolved in version [2.0.0](https://github.com/Bw2801/bezier-spline-kotlin/tree/bezier-spline-2.0.0).
